### ISSUE TITLE
More explicit links needed in how-to-switch-between-projects.md

### ISSUE THREAD

**Issue by Nortamo** [CSCfi/csc-user-guide#134]
In the last paragraph of `how-to-switch-between-projects.md`:

"See service-specific instructions under _Computing, Cloud and Data_ for more details about project selection in each service."

The customer will no be able to find the info based on this, so more detailed links should be inserted. If the information is not added to the different sections, that should also be done

**Comment by penikune** [comment]
I would move service-specific stuff to FAQ. See pull request:
https://github.com/CSCfi/csc-user-guide/pull/530

**Comment by penikune** [comment]
Resoved by pull request:
https://github.com/CSCfi/csc-user-guide/pull/555
