### ISSUE TITLE
How to format mail address in documentation?

### ISSUE THREAD

**Issue by Nortamo** [CSCfi/csc-user-guide#135]
Should email links in the documentation use the `mailto:` link.
I.e `[servicedesk@csc.fi](mailto:servicedesk@csc.fi)` and <mailto:servicedesk@csc.fi>

Or should there be no email links? It would be good to have one style for support emails.
Enforcing one style makes it much easier to check if all the emails are valid.

**Comment by attesillanpaa** [comment]
Mailto: would be a nice highlight, but how much more spam will it attract? I don't have a strong opinion. The checks have been very useful.

**Comment by penikune** [comment]
I am for [servicedesk@csc.fi](mailto:servicedesk@csc.fi), i.e. `[servicedesk@csc.fi](mailto:servicedesk@csc.fi)`. I don't think that it will attract any more spam than `servicedesk@csc.fi` without mailto link.

**Comment by attesillanpaa** [comment]
I agree for servicedesk. I'd also allow obviously mangled emails, like insert.name ät csc.fi. I guess it's easy to make the test skip those?

**Comment by attesillanpaa** [comment]
Added the mailto: version in styleguide.
