### ISSUE TITLE
Taito references

### ISSUE THREAD

**Issue by Nortamo** [CSCfi/csc-user-guide#136]
The documentation should keep mentions to Taito at a minimum, as this makes it easier to remove all the Taito related stuff once Taito goes away. 

Referencing Taito is ok when comparing changes to the new stuff, otherwise 
its kind of unnecessary. All references should also make sense for both new and old users. 
So if you write that some part or feature is only available on Taito, it would be a good idea to link to and explanation/instruction what Taito is so brand new users are not lost.

This issue serves as a way to track the Taito references and can be closed
once we take down Taito and remove all references.  Taito mentions can be found with
`grep -i Taito -r -n docs`

If you find a link belonging to some material you have written/ are responsible for, consider
removing it if it is not absolutely necessary. 
 
**Ok references** (They make sense in the context)

- [x] docs/apps/lastools.md:31:    For now, Puhti does not support running __.exe__ files so if you need to install/run the closed source tools, use the Taito cluster. [Taito & LAStools documentation](https://research.csc.fi/-/lastools)

- [x] docs/apps/gromacs.md:122:    to Taito or to a local machine for visual analysis.

- [x] docs/index.md:20:[Moving to Puhti from Taito and Sisu ](support/tutorials/puhti_quick.md)

- [x] docs/accounts/billing.md:3:For Puhti a new billing scheme is introduced. Taito and cloud billing is not changed.

- [x] docs/accounts/how-to-add-service-access-for-project.md:5:Taito; cloud services ePouta, cPouta and Rahti; storage services Allas

- [ ]  docs/support/tutorials/puhti_quick.md:1:# Moving to Puhti from Taito and Sisu

- [ ] docs/support/tutorials/puhti_quick.md:4:that you have previously used CSC cluster resources like Taito/Sisu. If not,

-[ ] docs/apps/trinity.md:85 ## Using autoTrinotate in Taito 

- [x] support/tutorials/nomachine-usage.md:17:- Easy way to leave jobs running e.g. on Taito-shell while logging off from laptop                                    

- [x] support/tutorials/nomachine-usage.md:49:5.   Once you see a black screen, you're there. Now right click at the black background and select "CSC local servers"  then "Taito/Puhti".                                                                                                                                                

- [x] support/tutorials/nomachine-usage.md:50:6.   You'll be prompted for your CSC password. Give it, and you'll have a terminal open on Taito. The terminal can display remote graphics. 
                                                                                                                                        

- [x] support/tutorials/nomachine-usage.md:64:- The default font in the terminal is ugly and small. To improve, start gnome-terminal (write `gnome-terminal` on the  command line) as the first thing, when you have a terminal in either Taito or Puhti. The font is then resizable on the fly.

**Borderline ok references** (They might be useful for some users)

- [x] docs/apps/openfoam.md:13:Different versions of OpenFOAM by OpenFOAM Foundation and OpenCFD are installed on [Taito and Puhti servers](https://research.csc.fi/csc-s-servers).

- [x] docs/accounts/how-to-switch-between-projects.md:17:* On Taito, the usage is by default charged to the billing

- [x] docs/apps/trinity.md:11:The Trinity module at CSC also includes TransDecoder and Trinonate tools (in Taito only) to anlyze the results of a Trinity run.

- [x] docs/apps/trinity.md:17:Taito: 2.3.2 , 2.4.0, 2.5.1, 2.6.5, 2.6.6

- [x] docs/apps/blast.md:39:-    interavtively with normal BLAST commans in Taito-shell

- [x] docs/apps/blast.md:41:-    in FGCI grid with gb command in Taito

**Unnecessary references** (Wrong or no useful information)

- [x] docs/apps/velvet.md:43:**Velvet programs available in Taito**

- [x] docs/apps/blast.md:43:To use the latest BLAST in Taito first give set up command :

- [x] docs/apps/blast.md:63:If your query sequence set contains less than 20 sequences then Taito-shell is probable the most effective platforms for the search. However, if your query set contains hundreds or thousands of sequences then utilizing the taito.csc.fi cluster is more  effective. For this kind of massive blast searches you can utilize the `pb` command in Puhti. _pb_ (Parallel BLAST) is designed for situations, where the query file includes large amount of sequences. It splits the query task into several subjobs, that can be run simultaneously using the resources of the server very effectively. For large sets of query sequences, _pb: can speed up the search up to 50 fold. Two sample _pb_ commands for puhti.csc.fi:

- [x] docs/support/tutorials/conda.md:126:as possible. Some environment module systems, such as the one in taito.csc.fi,
- [x] docs/support/tutorials/conda.md:128:taito.csc.fi it might be a good idea to run
- [x] docs/support/tutorials/conda.md:186:The examples below should work without modifications in taito.csc.fi and
- [x] docs/support/tutorials/conda.md:358:this environment can only be created in machine taito.csc.fi, if package
- [x] docs/support/support-howto.md:11:Your subject line should be descriptive. "Problem on Taito" is not a good subject line since it could be valid for many of the support emails we get. The support staff is a team. The subjects are the first thing that we see. A good subject will speed up the issue going to the right specialist.

- [x] docs/apps/trinity.md:29:Trinity should be used using interactively in Taito-shell or preferably through the batch job system. Below is a sample batch job file for Trinity.

- [x] docs/apps/trinity.md:70:More information about running batch jobs, can be found from the chapter three of the Taito user guide.

- [x] docs/apps/trinity.md:75:## Using autoTrinotate in Taito

- [x] docs/apps/trinity.md:77:In taito you can analyse the results of your Trinity job with autoTrininotate.

- [x] docs/apps/trinity.md:84:the Trinotate home page as the command has been slightly modified for Taito)

- [x] docs/apps/trinity.md:90:Note that autoTrinotate analysis can require much resources so you should execute the command in Taito-shell or as batch job

- [x] docs/apps/samtools.md:29:SAMtool jobs should either be run in Taito-shell or be executed as batch jobs. Below is a sample batch job file, 

- [x] docs/apps/samtools.md:30:for running a SAMtools job in Taito:

- [x] docs/apps/samtools.md:59:Check the chapter 3 of the Taito user guide for more information about running batch jobs.

- [ ] docs/apps/grid_blast.md:17:-     A valid grid certificate installed in the taito.csc.fi or taito-shell.csc.fi  server.

- [ ] docs/apps/grid_blast.md:24:BLAST jobs can be submitted to FGCI using **gb** (Grid Blast) command in taito.csc.fi or taito-shell.csc.fi. 

- [ ] docs/apps/grid_blast.md:42:First, login to taito.csc.fi and open a virtual terminal with screen command:

- [ ] docs/apps/grid_blast.md:92:Before you log out from Taito, you should check, which Taito login node (taito-login4.csc.fi or taito-login3.csc.fi ) you are using. The virtual terminal can be reconnected only from the same login node where it it was launched. Thus if your virtual terminal and grid BLAST job are running in the taito-login4.csc.fi server you must login to taito-login4.csc.fi in order to reconnect the virtual terminal with the screen -r command.

- [x] docs/apps/grid_blast.md:99:ssh taito-login4.csc.fi

**Comment by attesillanpaa** [comment]
Slightly cleaned up result from `grep -i Taito -r -n docs`

- [ ] docs/apps/grid_blast.md
- [ ] docs/apps/force.md
- [ ] docs/cloud/pouta/pouta-videos.md
- [ ] docs/support/tutorials/index.md
- [ ] docs/support/tutorials/puhti_quick.md
- [ ] docs/support/tutorials/mahti_quick.md
- [ ] docs/data/Allas/migration_tutorial.md
- [ ] docs/data/Allas/using_allas/a_commands.md
- [ ] docs/data/Allas/index.md
- [ ] docs/data/Allas/hpc-archive.md

**Comment by attesillanpaa** [comment]
Not many left:

- [ ] docs/apps/grid_blast.md
- [ ] docs/apps/force.md
- [ ] docs/cloud/pouta/pouta-videos.md
- [ ] docs/data/Allas/migration_tutorial.md

**Comment by ktiits** [comment]
docs/apps/force.md is ok in my opinion, it is in a link to a nice pdf, prepared by SYKE when Taito was in use.

**Comment by rkronberg** [comment]
Neither of the pouta-videos with Taito reference are available anymore. Will delete those entries and close this issue.
