### ISSUE TITLE
webhooks.md outdated

### ISSUE THREAD

**Issue by pitkant** [CSCfi/csc-user-guide#1635]
Context: Using webhooks with nginx-example

There are some differences between the [documentation](https://docs.csc.fi/cloud/rahti/tutorials/webhooks/) and what I observed while trying to follow the documentation.

From the documentation:

> ```
> spec:
>   triggers:
>   - type: GitHub
>     github:
>       SecretReference:
>         name: webhooksecret
> ```

Observed:
```
spec:
  triggers:
  - github:
      secret: <secret key>
    type: GitHub
```

From the documentation:

> Now the secret webhooksecret should have the WebHookSecretKey field:
> 
> 
> `oc get Secret webhooksecret -o yaml`

Observed:
When I attempted this, I got `Error from server (NotFound): secrets "webhooksecret" not found`. I copy-pasted the secret from BuildConfig file.

From the documentation:

> The WebHookSecretKey is encoded in base64, to decode it:
> 
> 
> `echo 'dGhpc19pc19hX2JhZF90b2tlbgo=' | base64 -d`

Observed:
There was no need to decode anything.

This issue may be specific to my case and not generalisable so I decided to open an issue instead of suggesting changes directly to webhooks.md.

**Comment by Socuz** [comment]
Hello,

Thank you, we have updated the documentation taking into account your remarks. (https://github.com/CSCfi/csc-user-guide/pull/1651)
