### ISSUE TITLE
Tables does not fit nicely on page

### ISSUE THREAD

**Issue by oscarkraemer** [CSCfi/csc-user-guide#17]
The tables on this page does not fit perfectly on this page? What would be the best way to change that?
https://csc-user-guide.rahti-int-app.csc.fi/cloud/vm-flavors-and-billing/

**Comment by attesillanpaa** [comment]
Hopefully to widen the column. There are already html forced line breaks in the long entries, but that does not seem to be enough. If site level tweaks don't work, we'll look into this again. But for now, this is "just" a formatting issue.

**Comment by attesillanpaa** [comment]
One option would be to delete those columns which have the same value for all flavors and include this info in the table caption.
e.g.
# Virtual machine flavors and billing unit rates

## cPouta flavours

### Standard flavors

| Flavor               | Cores | Memory | Memory/core | Billing Units/h |
| :-----------------:  | :---: | :----: | :---------: | :-------------: |
| **standard.tiny**    |     1 | 1GiB   | 1.0GiB      | 0.25 (0.5)      |
| **standard.small**   |     2 | 2GiB   | 1.0GiB      | 0.5 (1.0)       |
| **standard.medium**  |     3 | 4GiB   | 1.3GiB      | 1.0 (2.0)       |
| **standard.large**   |     4 | 8GiB   | 2.0GiB      | 2.0 (4.0)       |
| **standard.xlarge**  |     6 | 16GiB  | 2.6GiB      | 4.0 (8.0)       |
| **standard.xxlarge** |     8 | 32GiB  | 4.0GiB      | 8.0 (16.0)      |

Each standard flavor has **80GB root disk**.

**Comment by oscarkraemer** [comment]
That makes it harder to compare standard flavors to io-flavors. But maybe the right thing to do is to format the text to do new presentation format.

**Comment by oscarkraemer** [comment]
At the moment the https://csc-user-guide-dev.rahtiapp.fi/#cloud/pouta/vm-flavors-and-billing/ looks good. I don't know if you have changed something but IMO this issue could be resolved.
