### ISSUE TITLE
Cloud != Pouta

### ISSUE THREAD

**Issue by oscarkraemer** [CSCfi/csc-user-guide#18]
Cloud should not be the same thing as Pouta. There is Rahti and all kind of other cloud services.

**Comment by attesillanpaa** [comment]
This was intentional, but under discussion and Rahti documentation is still coming there, but... The options are to fill in Rahti stuff in between Pouta or separate the two into sub"pages". Cloud main "folder" likely remains (no service brand names at top level). A meeting has been set to discuss this. Join?

**Comment by oscarkraemer** [comment]
I could join the meeting, I do not have an invite.

**Comment by attesillanpaa** [comment]
There's now a branch called make_pouta. It has pouta in its own subfolder and I quickly copied rahti in another subfolder. The navigation is still only partially there, but is this now closer to what it should be? Do you want to create the Rahti pages yourself or work from the current stub?

**Comment by oscarkraemer** [comment]
I like this very much. I would be happy with this. Once this is merged I would consider this issue resolved. Also the documentation for compiling the mkdocs in the README is good.

One small thing IMO in the Coud/Pouta/Content page. One should probably not use headlines on the Coud/Pouta/Content page since those seems to create subsections in the left side panel. This is not an issue in the other pages, only on Coud/Pouta/Content. Attached picture. 
![Screen Shot 2019-04-26 at 10 50 33](https://user-images.githubusercontent.com/5577897/56792150-95e42380-6811-11e9-8990-5a5495a52cea.png)

**Comment by attesillanpaa** [comment]
We tried to side step this with the collabsible subsections in the left panel. I think this still needs some tuning.

**Comment by oscarkraemer** [comment]
IMO this issue could be resolved.
