### ISSUE TITLE
No visible page hierarchy 

### ISSUE THREAD

**Issue by oscarkraemer** [CSCfi/csc-user-guide#19]
At the moment if one goes to one of the link on https://csc-user-guide.rahti-int-app.csc.fi/cloud/ it is not clear what the hierarchy is. What is the best way to create a hierarchy?

Docs/Cloud
![Untitled](https://user-images.githubusercontent.com/5577897/56190549-1b5a1d80-6033-11e9-8fe0-e803660812b9.png)

</br>

"Docs/Get access to pouta" (but should probably be "Docs/Cloud/Get access to pouta")
![Untitled 2](https://user-images.githubusercontent.com/5577897/56190565-2319c200-6033-11e9-8691-341b6ec7e601.png)

**Comment by mlehtiva** [comment]
It seems that this would require some real extra level to the hierarchy, like Docs >> Cloud >> Get access to Pouta. 
In current Rahti manual the situation is clearer, as there's only one level :https://rahti.csc.fi/introduction/background/#container-orchestration.
Here they have this + / - thingy solution: https://solidity.readthedocs.io/en/v0.5.7/ 
Maybe in other Read the Docs examples they have even better solutions? https://readthedocs.org

**Comment by attesillanpaa** [comment]
My local mkdocs instance shows the middle folder in the top path, but does not show correctly the menu on the left. mkdocs serve complains about nav, though. Perhaps updating mkdocs versions might help?

**Comment by penikune** [comment]
Those pages referred to by Maria are done using Sphinx, not Mkdocs.
As for 'nav', it is there because newer versions of MkDocs complain about 'pages'.

**Comment by oscarkraemer** [comment]
The example Maria linked would meet my expectations/requirements.

**Comment by penikune** [comment]
With MkDocs it is not so simple. Here is the best MkDocs example I have found so far: http://readthedocs.sheets.ch
From our perspective, to make that work would mean that all cloud articles should be put (or imported) one after another to cloud.md.

**Comment by penikune** [comment]
This is maybe even better:
https://docs.neptune.ml/how-to-guides/how-to-index/
A good thing about this site is that it uses the Material theme, which is good also for another reason: it allows usage of Pymdown extensions (e.g. collapsible page elements, insertion of Markdown code from another file).

**Comment by oscarkraemer** [comment]
The present layout/hierarchy is good enough for resolving this issue IMO.
