### ISSUE TITLE
Minor thing: Not to helpful section on Allas and boto3, missing explanation of credentials file

### ISSUE THREAD

**Issue by merretbuurman** [CSCfi/csc-user-guide#2142]
I found this section not very helpful:
https://github.com/CSCfi/csc-user-guide/blob/master/docs/data/Allas/using_allas/python_boto3.md#configuring-s3-credentials

The links leads to another page that does not explain credentials files. I have an Allas Access Key and a Secret Key, and neither the section nor the linked page helped me how to use those for accessing my buckets via boto3. The linked page tells me to install all kinds of packages to then run allas-conf, but all I needed was how to add the secret key/access key to the ~/.aws/credentials` file.

This one then helped, which I found googling:
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#shared-credentials-file

Maybe this could be made easier for future S3 noobs :) Thanks!

**Comment by rkronberg** [comment]
Hi @merretbuurman and thanks for reporting! We will look into improving these instructions.
