### ISSUE TITLE
Site Description Missing

### ISSUE THREAD

**Issue by Aegil** [CSCfi/csc-user-guide#226]
The site_description is missing which means description of docs.csc.fi shows up as none in google.

site_description
Set the site description. This will add a meta tag to the generated HTML header.

default: null

<meta name="description" content="None">

**Comment by attesillanpaa** [comment]
Added this into top of mkdocs.yml:

Instructions to use the CSC supercomputer Puhti, Allas storage, Pouta, Rahti, software list, FAQ and tutorials.

Feel free to improve.

**Comment by attesillanpaa** [comment]
I'll close this for now. Feel free to improve the description.
