### ISSUE TITLE
Google doesn't find our content

### ISSUE THREAD

**Issue by attesillanpaa** [CSCfi/csc-user-guide#228]
This could be an issue with the windmill theme, which creates the "page hierarchy" with anchors. Whether this is the reason should be confirmed. If the theme is the reason, perhaps try what [NERSC](https://docs.nersc.gov/) is using? (Although I don't like their extra menu on the right).

**Comment by attesillanpaa** [comment]
Could also be due to broken sitemap.xml It does not get generated correctly, perhaps due to some version mismatch. Also, it should be built on the target machine to get the urls right.

**Comment by jussienko** [comment]
There is now branch with the NERSC theme as such (including still NERSC footers etc.): https://github.com/CSCfi/csc-user-guide/tree/material-theme

**Comment by attesillanpaa** [comment]
Thanks, but this does not seem to render correctly. Maybe we could try updating the rahti container libraries? @juhanikataja :)

**Comment by attesillanpaa** [comment]
@juhanikataja fixed the creation of the sitemap. Now google found at least on page in the apps (with site:docs.csc.fi) so perhaps this is now fixed. We might still want to change the theme from windmill to material, but the work on tuning the look-and-feel is still incomplete. Now its urgency is lower, though. And we don't have that "someone" to do it. Volunteers?

**Comment by jlento** [comment]
If I do a Google search "csc puhti sbatch", it does not direct to docs.csc.fi.

**Comment by attesillanpaa** [comment]
Maybe that's because G hasn't really crawled the site yet? I recall earlier even using site:docs.csc.fi didn't result in anything in the subfolders.

**Comment by attesillanpaa** [comment]
Thanks Juhani! This seems to work.

**Comment by attesillanpaa** [comment]
There are still issues with this. Help needed to localize the materials-theme. Ask me if you want access to google search console results to debug what's wrong.

**Comment by attesillanpaa** [comment]
This seems to improve little by little. If you have ideas to improve google visibility please suggest, but otherwise I'll close this issue.
