### ISSUE TITLE
Pouta-faq is missing from the documentation 

### ISSUE THREAD

**Issue by oscarkraemer** [CSCfi/csc-user-guide#28]
The documentation on https://research.csc.fi/pouta-faq is missing/incomplete in the csc-user-guide.

**Comment by attesillanpaa** [comment]
I think we'll move away from service/subfolder FAQs and make one general under Support. Are all those FAQ entries still relevant?

**Comment by oscarkraemer** [comment]
Some of them are very Pouta specific FAQ but some would probably fit under a more general topic. 

These topics are not relevant anymore:
* How do I migrate my data away from legacy volumes?
* `Can I access my CSC home/wrkdir/project directories from ePouta?` can probably removed.

Then there are some of them that just points to other topic, I don't know if there is any point of recreating those FAQ.

**Comment by attesillanpaa** [comment]
I added now most of them. The wrk-access is referred to from e.g. is pouta backed up -entry. Could you check that one and perhaps mention object storage/allas in it?

**Comment by oscarkraemer** [comment]
I feel that maybe a better solution would be to remove the table and write something like `Some other CSC services have backups, so depending on the type and amount of data users can consider copying or using in parallel one of the other CSC Data services .` and link to one of the topics in the Data section in the user-guide. My understanding is that Allas will not be under the Pouta topic in the future so I'm a bit hesitated to mention the backup state of Allas.

**Comment by jarnolaitinen** [comment]
In my opinion the correct answer is just "No."
Puhti does not have any back-up. 
Allas does not have a back-up.
IDA is not CSC's service as such and it is not a back-up service either.
Allas could be used as a place to make a copy of files from Puhti or Pouta VM.

**Comment by attesillanpaa** [comment]
FAQ in place and no backups promised.
