### ISSUE TITLE
Does allas have backups?

### ISSUE THREAD

**Issue by oscarkraemer** [CSCfi/csc-user-guide#287]
https://github.com/CSCfi/csc-user-guide/blob/master/docs/data/Allas/introduction.md

There should probably be mentions that there is "no backups" in one of sections. In the end of the page there is some mentioned how the data is stored. I think there should be a dedicated section about how the data is stored .

**Comment by attesillanpaa** [comment]
At the very end there is a recommendation to take backups (to prepare against accidental deletion). Perhaps how data is stored is not for the intro, but maybe a link somewhere outside?
