### ISSUE TITLE
Indentation of pages with child pages

### ISSUE THREAD

**Issue by galfthan** [CSCfi/csc-user-guide#367]
In the new style pages with "child" pages is indented wrongly in Menu. In picture "Running Jobs" should be at the same level as "Module environment". In old style the arrow was aligned with the others titles.

![menu](https://user-images.githubusercontent.com/4047121/73344915-d171b980-428b-11ea-8fc5-04a5e55e31ee.png)

**Comment by johannesnyman** [comment]
Yea it's a bit off. I'll have a look soon

It's not the easiest as there is no padding or margin for the arrows. The "extra" width comes from the arrow icon itself (which is different as previously). And we also don't want to affect the arrows on the main menu (like next to Computing). 

But there's always a way with CSS to have an exception of an exception

**Comment by johannesnyman** [comment]
Indentation fixed. Made a more reasonable scroll bar too if the menu gets too tall. https://csc-guide-preview.rahtiapp.fi/origin/css_indentation/
