### ISSUE TITLE
Landing page is too bland, what do you think?

### ISSUE THREAD

**Issue by penikune** [CSCfi/csc-user-guide#524]
By the landing page I mean this:
* [Docs CSC](https://docs.csc.fi/)

Isn't it a bit too generic? Would it be hard to do something like this:
* [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)

**Comment by attesillanpaa** [comment]
The contrast to other pages is big, but then plainness focuses into content. If the landing page has only few elements, they get attention, which is valuable. 

Related to the looks, what would the graphics be of? Puhti/Mahti/Allas -pics?

**Comment by attesillanpaa** [comment]
A competing suggestion: add a schematic picture of the CSC (hardware) environment on the front page (see the latest SR-COMP presentation for a starting point). How about other services (like SD Desktop).

**Comment by attesillanpaa** [comment]
Current landing page is not so bland anymore, but quite pragmatic. If new ideas emerge, let's reopen.
