### ISSUE TITLE
Broken external links found

### ISSUE THREAD

**Issue by penikune** [CSCfi/csc-user-guide#549]
GIS (Kylli fixes):
https://pysal.readthedocs.io/en/latest/
https://mapbox.github.io/rasterio/
https://pythonhosted.org/spyder/
https://github.com/csc-training/geocomputing/tree/master/python/focal_mean
http://spatialdemography.org/essential-python-geospatial-libraries/
http://geoexamples.blogspot.com/
https://research.csc.fi/gis_data_in_taito
https://cran.r-project.org/web/packages/geoRglm/index.html
https://cran.r-project.org/web/packages/spatial.tools/index.html
https://github.com/csc-training/geocomputing/tree/master/machineLearning/cnn
https://github.com/jblindsay/whitebox-tools/LICENSE.txt

http://support.rc.nectar.org.au/technical_guides/security.html
https://www.fitsm.eu/wp-content/uploads/sites/3/2018/05/FitSM-0_Overview_and_vocabulary.pdf

https://github.com/Digipalvelutehdas/container-course-material
https://docs.okd.io/latest/architecture/core_concepts/index.html
https://docs.okd.io/latest/dev_guide/deployments/deployment_strategies.html
https://docs.okd.io/latest/cli_reference/index.html

**Comment by lvarin** [comment]
I will create a PR to fix:
https://github.com/Digipalvelutehdas/container-course-material
https://docs.okd.io/latest/architecture/core_concepts/index.html
https://docs.okd.io/latest/dev_guide/deployments/deployment_strategies.html
https://docs.okd.io/latest/cli_reference/index.html

**Comment by lvarin** [comment]
https://github.com/CSCfi/csc-user-guide/pull/702

**Comment by attesillanpaa** [comment]
muutama vielä jäljellä:

docs/apps/r-env-for-gis.md:* [geoRglm](https://cran.r-project.org/web/packages/geoRglm/index.html) - functions for inference in generalised linear spatial models, extension to the `geoR` package
docs/apps/r-env-for-gis.md:* [spatial.tools](https://cran.r-project.org/web/packages/spatial.tools/index.html) - to enhance the core functionality of the package `raster`, including a parallel processing engine for use with rasters
docs/apps/solaris.md:* [CSC example pipeline](https://github.com/csc-training/geocomputing/tree/master/machineLearning/cnn)

**Comment by ktiits** [comment]
GIS-links done.
