### ISSUE TITLE
Docs CSC or CSC Docs?

### ISSUE THREAD

**Issue by jlento** [CSCfi/csc-user-guide#55]
Is it "Docs CSC" or "CSC Docs"? My vote for "Docs CSC" since it is docs.csc.fi :)

**Comment by Nortamo** [comment]
You mean like on the front page?

I would say we use either Docs CSC or then some complete form, e.g. 
CSC Documentation.

**Comment by penikune** [comment]
CSCdocs

**Comment by penikune** [comment]
Poll situation ([see here](https://rc.csc.fi/channel/docs.csc.fi)):
+2 CSC Docs
+2 Docs CSC

**Comment by Nortamo** [comment]
Stagnant
