### ISSUE TITLE
Missing documentation for compute

### ISSUE THREAD

**Issue by galfthan** [CSCfi/csc-user-guide#62]
TODO:
- [x] example scripts: Multinode GPU
- [x] example scripts: sing GPU
- [x] example scripts: with nvme
- [x] disk.md: Discuss cleaning

Done:
- [x] sinfo, sacct 
- [x] compiling: hpcx is default, text should reflect in final section
- [x] compiling: FIXME
- [x] quota

Needs planning:
- [x] FMI documentation: specs,  partitions, usage, logging in, ... At FMI and not our responsibility?

**Comment by penikune** [comment]
A side remark: For node specs, partition specs and clean up things, the best location would be research.csc.fi. The primary scope of these docs in is to serve as a how-to-guide.

**Comment by galfthan** [comment]
No,research.csc.fi is for presenting on a higher level services and the compute capabilities. In docs.csc.fi we have the detailed specs. This is the same as for taito sisu.

**Comment by penikune** [comment]
I don't fully agree, but this issue is not the best place to discuss about it.
