### ISSUE TITLE
Accessibility evaluation report

### ISSUE THREAD

**Issue by johanneshiekkasaari** [CSCfi/csc-user-guide#797]
An accessibility evaluation was conducted of docs.csc.fi in November/December 2020. 

Here are all problems they found. Number of + indicates how severe the problem is. See details and suggestions in the report

## Visuals
- [x] Contrast of text  ++++
- [x] Contrast of interface components ++++
- [x] Contrast of link text +++
- [ ] Text alternatives have defects +++
- [x] Keyboard focus indicator ++

## Structure
- [ ] Missing titles in iframes ++++ 
- <del>[ ] Heading structure issues ++ </del>
- [x] Page regions (too many) ++
- <del>[ ] Applications page title does not include "Applications" ++</del>
- [x] HTML validation +

## Navigation
- [x] Keyboard navigation not possible  ++++
- [x] Keyboard navigation trap (at least with Safari) ++++
- <del>[ ] Focus order </del>

## Search 
- [x] Missing labels (text alternatives) ++++
- [x] Keyboard and assistive technology use +++
- [x] Single-key shortcut +++
- [x] Search overlay (dark gray) can remain active +++
- <del>[ ] Search result relationships ++</del>

## General
- [ ] Reliance on sensory characteristics in instructions +
- [x] Change of user interface without warning (github) + 

You can find the full report here https://wiki.eduuni.fi/display/CSCSCS/Docs.csc.fi+service

**Comment by johannesnyman** [comment]
Made a working branch "accessibility" for this

**Comment by johannesnyman** [comment]
**Heading structure issues ++**
Suggestion was to change some of the <h1> (TOC, search results) to smaller headings. This is quite hard as those are generated and not out of our reach. **Not implemented**

**Comment by johannesnyman** [comment]
**Applications page titles do not include "Applications" ++**
It's not possible to define the page title (the text in the browser tab) in .md files. It gets it automatically from the mkdocs.yml file which now says those "By discipline" "By system". **Not implemented**

**Comment by johannesnyman** [comment]
**Focus order and search result relationships**
Some thing in search bar are rather hard to fix as there is no html to change for individual search results (they are generated). For me at least the search is mostly usable with keyboard (tab and arrow keys)
