### ISSUE TITLE
Create a HPC/CSC dictionary

### ISSUE THREAD

**Issue by attesillanpaa** [CSCfi/csc-user-guide#860]
CSC environment / HPC is full of acronyms and terms likely foreign to new HPC users. A vocabulary/dictionary would be useful and could link to relevant parts of docs / CSC documentation. Location in FAQ?

**Comment by attesillanpaa** [comment]
Mkdocs has a tooltips feature. Perhaps use the glossary as source to create tooltips for all occurrences in body text?

**Comment by joonas-somero** [comment]
Definitions can now be added to csc-overrides/assets/glossaries/hpc.md which then get shown as tooltips on a corresponding term/acronym. Closing the issue as completed.
